spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/spring-boot?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  profiles:
    include: api
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  type-aliases-package: com.pactera.business.domain
  mapper-locations: classpath:mapper/*.xml
mapper:
  mappers: com.pactera.base.core.Mapper
  not-empty: false
  identity: MYSQL
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql