# tomcat server
server:
  port: 80
# log level
logging:
  level:
    root: info
    com.fasterxml: warn 
    org.springframework: warn
    springfox.documentation: warn
    org.springframework.boot.context.embedded.tomcat: info
# application start
spring:
  profiles:
    active: dev